name: "kitti360" #same labels as when the model was trained on kitti360
labels: # original IDs
  0: "unlabeled"
  1: "ego vehicle"
  2: "rectification border"
  3: "out of roi"
  4: "static"
  5: "dynamic"
  6: "ground"
  7: "road"
  8: "sidewalk"
  9: "parking"
  10: "rail track"
  11: "building"
  12: "wall"
  13: "fence"
  14: "guard rail"
  15: "bridge"
  16: "tunnel"
  17: "pole"
  18: "polegroup"
  19: "traffic light"
  20: "traffic sign"
  21: "vegetation"
  22: "terrain"
  23: "sky"
  24: "person"
  25: "rider"
  26: "car"
  27: "truck"
  28: "bus"
  29: "caravan"
  30: "trailer"
  31: "train"
  32: "motorcycle"
  33: "bicycle"
  34: "garage"
  35: "gate"
  36: "stop"
  37: "smallpole"
  38: "lamp"
  39: "trash bin"
  40: "vending machine"
  41: "box"
  42: "unknown construction"
  43: "unknown vehicle"
  44: "unknown object"
  -1: "license plate"
color_map:
  0: [0, 0, 0]
  1: [0, 0, 0]
  2: [0, 0, 0]
  3: [0, 0, 0]
  4: [0, 0, 0]
  5: [111, 74, 0]
  6: [81, 0, 81]
  7: [128, 64, 128]
  8: [244, 35, 232]
  9: [250, 170, 160]
  10: [230, 150, 140]
  11: [70, 70, 70]
  12: [102, 102, 156]
  13: [190, 153, 153]
  14: [180, 165, 180]
  15: [150, 100, 100]
  16: [150, 120, 90]
  17: [153, 153, 153]
  18: [153, 153, 153]
  19: [250, 170, 30]
  20: [220, 220, 0]
  21: [107, 142, 35]
  22: [152, 251, 152]
  23: [70, 130, 180]
  24: [220, 20, 60]
  25: [255, 0, 0]
  26: [0, 0, 142]
  27: [0, 0, 70]
  28: [0, 60, 100]
  29: [0, 0, 90]
  30: [0, 0, 110]
  31: [0, 80, 100]
  32: [0, 0, 230]
  33: [119, 11, 32]
  34: [64, 128, 128]
  35: [190, 153, 153]
  36: [150, 120, 90]
  37: [153, 153, 153]
  38: [0, 64, 64]
  39: [0, 128, 192]
  40: [128, 64, 0]
  41: [64, 64, 128]
  42: [102, 0, 0]
  43: [51, 0, 51]
  44: [32, 32, 32]
  -1: [  0,  0,142]
learning_map:
  0: 0
  1: 0
  2: 0
  3: 0
  4: 0
  5: 0
  6: 0
  7: 1
  8: 2
  9: 1
  10: 1
  11: 3
  12: 4
  13: 5
  14: 3
  15: 3
  16: 3
  17: 6
  18: 6
  19: 7
  20: 8
  21: 9
  22: 10
  23: 11
  24: 12
  25: 13
  26: 14
  27: 15
  28: 16
  29: 14
  30: 14
  31: 17
  32: 18
  33: 19
  34: 3
  35: 3
  36: 3
  37: 6
  38: 6
  39: 6
  40: 6
  41: 6
  42: 0
  43: 0
  44: 0
  -1: 14
learning_map_inv:
  0: 0
  1: 7
  2: 8
  3: 11
  4: 12
  5: 13
  6: 17
  7: 19
  8: 20
  9: 21
  10: 22
  11: 23
  12: 24
  13: 25
  14: 26
  15: 27
  16: 28
  17: 31
  18: 32
  19: 33
learning_ignore:
  0: True     #'unlabeled'
  1: False    #'road'
  2: False    #'sidewalk'
  3: False    #'building'
  4: False    #'wall'
  5: False    #'fence'
  6: False    #'pole'
  7: False    #'traffic light'
  8: False    #'traffic sign'
  9: False    #'vegetation'
  10: False   #'terrain'
  11: True    #'sky'
  12: False   #'person'
  13: False   #'rider'
  14: False   #'car'
  15: False   #'truck'
  16: False   #'bus'
  17: False   #'train'
  18: False   #'motorcycle'
  19: False   #'bicycle'
split: # sequence numbers
  train:
    #- 0
    #- 1
    #- 2
    #- 3
    #- 4
    #- 5
    #- 6
    #- 7
  valid:
    - 1
    - 2
    - 3
    - 4
    - 5
  test:
    #- 9
    #- 10
    #- 11
    #- 12
    #- 13
    #- 14
    #- 15
    #- 16
    #- 17
    #- 18
    #- 19
    #- 20
    #- 21

    